

development:
  adapter: postgresql
  database: kelp_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: kelp_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: kelp_production
  pool: 5
  timeout: 5000